version: '3.7'

services:
  app:
    build: .docker/php-fpm
    container_name: app-mesha-${APP_ENV}
    restart: always
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: .docker/nginx
    container_name: nginx-mesha-${APP_ENV}
    restart: always
    tty: true
    ports:
      - "${NGINX_PORT-80}:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: postgres:12.3
    container_name: db-mesha-${APP_ENV}
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
